-- Foundation Fund App - Supabase schema (GENERATED FROM LIVE)
-- Project: mlnzxhuozuyidpxepxex
--
-- Generated by scripts/dump-supabase-schema.py. DO NOT EDIT BY HAND:
-- make changes in supabase/migrations/NNNNNN_description.sql, apply them
-- to the live project, then regenerate with:
--   SUPABASE_ACCESS_TOKEN=... SUPABASE_PROJECT_REF=... \
--     python3 scripts/dump-supabase-schema.py > supabase/schema.sql
--
-- This file provisions an EMPTY public schema; it is a snapshot of
-- what production runs, not an incremental migration.

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Tables (columns + primary key / unique / check inline)

CREATE TABLE IF NOT EXISTS public.account_transactions (
    CONSTRAINT "account_transactions_pkey" PRIMARY KEY (id),
    CONSTRAINT "account_transactions_direction_check" CHECK ((direction = ANY (ARRAY['in'::text, 'out'::text]))),
    CONSTRAINT "account_transactions_amount_check" CHECK ((amount > (0)::numeric)),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    account_id uuid NOT NULL,
    date date DEFAULT CURRENT_DATE NOT NULL,
    direction text NOT NULL,
    amount numeric NOT NULL,
    particulars text NOT NULL,
    remarks text,
    transfer_id uuid,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.accounts (
    CONSTRAINT "accounts_pkey" PRIMARY KEY (id),
    CONSTRAINT "accounts_opening_balance_check" CHECK ((opening_balance >= (0)::numeric)),
    CONSTRAINT "accounts_type_check" CHECK ((type = ANY (ARRAY['bank'::text, 'cash'::text]))),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    type text NOT NULL,
    opening_balance numeric DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.audit_log (
    CONSTRAINT "audit_log_pkey" PRIMARY KEY (id),
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    actor_id uuid,
    actor_email text,
    action text NOT NULL,
    target_table text,
    target_id text,
    details jsonb DEFAULT '{}'::jsonb,
    ip text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.donations (
    CONSTRAINT "donations_pkey" PRIMARY KEY (id),
    CONSTRAINT "donations_receipt_no_key" UNIQUE (receipt_no),
    CONSTRAINT "donations_amount_positive" CHECK ((amount > (0)::numeric)),
    CONSTRAINT "donations_extra_amount_check" CHECK ((extra_amount >= (0)::numeric)),
    CONSTRAINT "donations_method_check" CHECK ((method = ANY (ARRAY['cash'::text, 'bkash'::text, 'nagad'::text, 'bank'::text]))),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    member_id uuid NOT NULL,
    amount numeric NOT NULL,
    date date DEFAULT CURRENT_DATE NOT NULL,
    method text NOT NULL,
    receipt_no text NOT NULL,
    donation_month text,
    received_by text,
    collected_by uuid,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    batch_id uuid,
    donation_end_month text,
    coverage_start_month text,
    coverage_end_month text,
    extra_amount numeric DEFAULT 0 NOT NULL,
    note text
);

CREATE TABLE IF NOT EXISTS public.expense_categories (
    CONSTRAINT "expense_categories_pkey" PRIMARY KEY (id),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.expenses (
    CONSTRAINT "expenses_pkey" PRIMARY KEY (id),
    CONSTRAINT "expenses_amount_positive" CHECK ((amount > (0)::numeric)),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    category text NOT NULL,
    amount numeric NOT NULL,
    date date DEFAULT CURRENT_DATE NOT NULL,
    description text,
    proof_url text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.member_pledge_history (
    CONSTRAINT "member_pledge_history_pkey" PRIMARY KEY (id),
    CONSTRAINT "member_pledge_history_monthly_amount_check" CHECK ((monthly_amount >= (0)::numeric)),
    CONSTRAINT "member_pledge_history_effective_from_month_check" CHECK ((effective_from_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'::text)),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    member_id uuid NOT NULL,
    monthly_amount numeric NOT NULL,
    effective_from_month text NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    note text
);

CREATE TABLE IF NOT EXISTS public.members (
    CONSTRAINT "members_pkey" PRIMARY KEY (id),
    CONSTRAINT "members_pledge_non_negative" CHECK ((monthly_pledge >= (0)::numeric)),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    phone text,
    address text,
    join_date date DEFAULT CURRENT_DATE NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    monthly_pledge numeric DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    member_code text
);

CREATE TABLE IF NOT EXISTS public.notices (
    CONSTRAINT "notices_pkey" PRIMARY KEY (id),
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    is_active boolean DEFAULT true,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.notifications (
    CONSTRAINT "notifications_pkey" PRIMARY KEY (id),
    CONSTRAINT "notifications_channel_check" CHECK ((channel = ANY (ARRAY['whatsapp'::text, 'sms'::text]))),
    CONSTRAINT "notifications_status_check" CHECK ((status = ANY (ARRAY['sent'::text, 'failed'::text, 'skipped'::text]))),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    donation_id uuid,
    member_id uuid,
    channel text DEFAULT 'whatsapp'::text NOT NULL,
    recipient text NOT NULL,
    status text DEFAULT 'skipped'::text NOT NULL,
    provider_message_id text,
    error text,
    sent_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.payment_allocations (
    CONSTRAINT "payment_allocations_pkey" PRIMARY KEY (id),
    CONSTRAINT "uq_payment_allocations_payment_month_type" UNIQUE (payment_id, month, allocation_type),
    CONSTRAINT "payment_allocations_amount_check" CHECK ((amount >= (0)::numeric)),
    CONSTRAINT "payment_allocations_allocation_type_check" CHECK ((allocation_type = ANY (ARRAY['pledge'::text, 'advance'::text, 'unallocated'::text]))),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    payment_id uuid NOT NULL,
    member_id uuid NOT NULL,
    month text,
    amount numeric NOT NULL,
    allocation_type text NOT NULL,
    note text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.reminder_log (
    CONSTRAINT "reminder_log_pkey" PRIMARY KEY (id),
    CONSTRAINT "reminder_log_channel_check" CHECK ((channel = ANY (ARRAY['whatsapp'::text, 'sms'::text]))),
    CONSTRAINT "reminder_log_status_check" CHECK ((status = ANY (ARRAY['sent'::text, 'failed'::text, 'skipped'::text]))),
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    member_id uuid NOT NULL,
    month text NOT NULL,
    channel text DEFAULT 'whatsapp'::text NOT NULL,
    recipient text NOT NULL,
    status text DEFAULT 'skipped'::text NOT NULL,
    error text,
    sent_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    CONSTRAINT "users_pkey" PRIMARY KEY (id),
    CONSTRAINT "users_role_valid" CHECK ((role = ANY (ARRAY['member'::text, 'treasurer'::text, 'admin'::text]))),
    id uuid NOT NULL,
    email text,
    name text,
    phone text,
    role text DEFAULT 'member'::text NOT NULL,
    is_approved boolean DEFAULT false NOT NULL,
    member_id uuid,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Foreign keys (after all tables exist)
ALTER TABLE public.account_transactions ADD CONSTRAINT "account_transactions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.account_transactions ADD CONSTRAINT "account_transactions_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;
ALTER TABLE public.accounts ADD CONSTRAINT "accounts_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.donations ADD CONSTRAINT "donations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.donations ADD CONSTRAINT "donations_collected_by_fkey" FOREIGN KEY (collected_by) REFERENCES users(id);
ALTER TABLE public.donations ADD CONSTRAINT "donations_member_id_fkey" FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;
ALTER TABLE public.expenses ADD CONSTRAINT "expenses_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.member_pledge_history ADD CONSTRAINT "member_pledge_history_member_id_fkey" FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;
ALTER TABLE public.member_pledge_history ADD CONSTRAINT "member_pledge_history_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.notices ADD CONSTRAINT "notices_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.notifications ADD CONSTRAINT "notifications_member_id_fkey" FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL;
ALTER TABLE public.notifications ADD CONSTRAINT "notifications_sent_by_fkey" FOREIGN KEY (sent_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.notifications ADD CONSTRAINT "notifications_donation_id_fkey" FOREIGN KEY (donation_id) REFERENCES donations(id) ON DELETE CASCADE;
ALTER TABLE public.payment_allocations ADD CONSTRAINT "payment_allocations_member_id_fkey" FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;
ALTER TABLE public.payment_allocations ADD CONSTRAINT "payment_allocations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.payment_allocations ADD CONSTRAINT "payment_allocations_payment_id_fkey" FOREIGN KEY (payment_id) REFERENCES donations(id) ON DELETE CASCADE;
ALTER TABLE public.reminder_log ADD CONSTRAINT "reminder_log_member_id_fkey" FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;
ALTER TABLE public.users ADD CONSTRAINT "users_member_id_fkey" FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL;
ALTER TABLE public.users ADD CONSTRAINT "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- 4. Indexes (constraint backing indexes omitted)
CREATE INDEX idx_account_transactions_account ON public.account_transactions USING btree (account_id);
CREATE INDEX idx_account_transactions_date ON public.account_transactions USING btree (date DESC);
CREATE INDEX idx_account_transactions_transfer ON public.account_transactions USING btree (transfer_id) WHERE (transfer_id IS NOT NULL);
CREATE INDEX idx_audit_log_actor ON public.audit_log USING btree (actor_id);
CREATE INDEX idx_audit_log_created ON public.audit_log USING btree (created_at);
CREATE INDEX idx_donations_batch_id ON public.donations USING btree (batch_id);
CREATE INDEX idx_donations_collected_by ON public.donations USING btree (collected_by);
CREATE INDEX idx_donations_created_by ON public.donations USING btree (created_by);
CREATE INDEX idx_donations_date ON public.donations USING btree (date);
CREATE INDEX idx_donations_member_date ON public.donations USING btree (member_id, date);
CREATE INDEX idx_donations_member_id ON public.donations USING btree (member_id);
CREATE INDEX idx_expenses_created_by ON public.expenses USING btree (created_by);
CREATE INDEX idx_member_pledge_history_member_month ON public.member_pledge_history USING btree (member_id, effective_from_month);
CREATE UNIQUE INDEX idx_members_member_code ON public.members USING btree (member_code) WHERE (member_code IS NOT NULL);
CREATE INDEX idx_notifications_donation ON public.notifications USING btree (donation_id);
CREATE INDEX idx_notifications_member ON public.notifications USING btree (member_id);
CREATE INDEX idx_payment_allocations_member_month ON public.payment_allocations USING btree (member_id, month);
CREATE INDEX idx_payment_allocations_month ON public.payment_allocations USING btree (month);
CREATE INDEX idx_payment_allocations_payment ON public.payment_allocations USING btree (payment_id);
CREATE INDEX idx_reminder_log_member ON public.reminder_log USING btree (member_id);
CREATE INDEX idx_reminder_log_member_month ON public.reminder_log USING btree (member_id, month);
CREATE INDEX idx_reminder_log_month ON public.reminder_log USING btree (month);
CREATE INDEX idx_users_member_id ON public.users USING btree (member_id);

-- 5. Row Level Security
ALTER TABLE public.account_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.member_pledge_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminder_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 6. Policies (verbatim from the live catalog)
CREATE POLICY "account_transactions_insert_staff" ON public.account_transactions
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "account_transactions_select_staff" ON public.account_transactions
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "accounts_manage_staff" ON public.accounts
  FOR ALL TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])))
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "accounts_select_staff" ON public.accounts
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "audit_log_select_admin" ON public.audit_log
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = 'admin'::text));
CREATE POLICY "donations_delete_staff" ON public.donations
  FOR DELETE TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "donations_insert_staff" ON public.donations
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "donations_select_own" ON public.donations
  FOR SELECT TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = auth.uid()) AND (users.member_id = donations.member_id)))));
CREATE POLICY "donations_select_staff" ON public.donations
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "donations_update_staff" ON public.donations
  FOR UPDATE TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "expense_categories_delete_admin" ON public.expense_categories
  FOR DELETE TO PUBLIC
  USING ((get_my_role() = 'admin'::text));
CREATE POLICY "expense_categories_insert_admin" ON public.expense_categories
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = 'admin'::text));
CREATE POLICY "expense_categories_select_staff" ON public.expense_categories
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "expense_categories_update_admin" ON public.expense_categories
  FOR UPDATE TO PUBLIC
  USING ((get_my_role() = 'admin'::text));
CREATE POLICY "expenses_delete_admin" ON public.expenses
  FOR DELETE TO PUBLIC
  USING ((get_my_role() = 'admin'::text));
CREATE POLICY "expenses_insert_staff" ON public.expenses
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "expenses_select_staff" ON public.expenses
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "expenses_update_staff" ON public.expenses
  FOR UPDATE TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "pledge_history_insert_staff" ON public.member_pledge_history
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "pledge_history_select_own" ON public.member_pledge_history
  FOR SELECT TO PUBLIC
  USING ((member_id = get_my_member_id()));
CREATE POLICY "pledge_history_select_staff" ON public.member_pledge_history
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "members_delete_admin" ON public.members
  FOR DELETE TO PUBLIC
  USING ((get_my_role() = 'admin'::text));
CREATE POLICY "members_insert_staff" ON public.members
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "members_select_own" ON public.members
  FOR SELECT TO PUBLIC
  USING ((id = get_my_member_id()));
CREATE POLICY "members_select_staff" ON public.members
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "members_update_own" ON public.members
  FOR UPDATE TO PUBLIC
  USING ((id = get_my_member_id()))
  WITH CHECK ((id = get_my_member_id()));
CREATE POLICY "members_update_staff" ON public.members
  FOR UPDATE TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "notices_delete_admin" ON public.notices
  FOR DELETE TO PUBLIC
  USING ((get_my_role() = 'admin'::text));
CREATE POLICY "notices_insert_admin" ON public.notices
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = 'admin'::text));
CREATE POLICY "notices_select_all" ON public.notices
  FOR SELECT TO PUBLIC
  USING (true);
CREATE POLICY "notices_update_admin" ON public.notices
  FOR UPDATE TO PUBLIC
  USING ((get_my_role() = 'admin'::text));
CREATE POLICY "notifications_insert_staff" ON public.notifications
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "notifications_select_staff" ON public.notifications
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "payment_allocations_delete_admin" ON public.payment_allocations
  FOR DELETE TO PUBLIC
  USING ((get_my_role() = 'admin'::text));
CREATE POLICY "payment_allocations_insert_staff" ON public.payment_allocations
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "payment_allocations_select_own" ON public.payment_allocations
  FOR SELECT TO PUBLIC
  USING ((member_id = get_my_member_id()));
CREATE POLICY "payment_allocations_select_staff" ON public.payment_allocations
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "reminder_log_insert_staff" ON public.reminder_log
  FOR INSERT TO PUBLIC
  WITH CHECK ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "reminder_log_select_staff" ON public.reminder_log
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "users_admin_all" ON public.users
  FOR ALL TO PUBLIC
  USING ((get_my_role() = 'admin'::text))
  WITH CHECK ((get_my_role() = 'admin'::text));
CREATE POLICY "users_insert_self" ON public.users
  FOR INSERT TO PUBLIC
  WITH CHECK (((auth.uid() = id) AND (role = 'member'::text) AND (is_approved = false) AND (member_id IS NULL)));
CREATE POLICY "users_read_self" ON public.users
  FOR SELECT TO PUBLIC
  USING (((auth.uid() = id) OR (get_my_role() = 'admin'::text)));
CREATE POLICY "users_read_staff" ON public.users
  FOR SELECT TO PUBLIC
  USING ((get_my_role() = ANY (ARRAY['admin'::text, 'treasurer'::text])));
CREATE POLICY "users_update_self_profile" ON public.users
  FOR UPDATE TO PUBLIC
  USING (((auth.uid() = id) OR (get_my_role() = 'admin'::text)))
  WITH CHECK (((get_my_role() = 'admin'::text) OR ((auth.uid() = id) AND (role = get_my_role()) AND (is_approved = get_my_is_approved()) AND (NOT (member_id IS DISTINCT FROM get_my_member_id())))));

-- 7. Functions (verbatim definitions; trailing line lists which roles
--    hold EXECUTE - only service_role may run the payment RPCs)
-- admin_delete_user: authenticated=EXECUTE, service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.admin_delete_user(target_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
BEGIN
  IF get_my_role() <> 'admin' THEN
    RAISE EXCEPTION 'Admins only';
  END IF;

  IF target_user_id = auth.uid() THEN
    RAISE EXCEPTION 'নিজের অ্যাকাউন্ট মুছে ফেলা যাবে না';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = target_user_id) THEN
    RAISE EXCEPTION 'User not found';
  END IF;

  UPDATE public.donations SET created_by = NULL WHERE created_by = target_user_id;
  UPDATE public.donations SET collected_by = NULL WHERE collected_by = target_user_id;
  UPDATE public.member_pledge_history SET created_by = NULL WHERE created_by = target_user_id;
  UPDATE public.payment_allocations SET created_by = NULL WHERE created_by = target_user_id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = target_user_id;
  UPDATE public.notices SET created_by = NULL WHERE created_by = target_user_id;
  DELETE FROM auth.users WHERE id = target_user_id;
END;
$function$;

-- backfill_payment_allocations: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.backfill_payment_allocations()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    r RECORD;
    allocation RECORD;
    v_pledge_history JSONB;
BEGIN
    FOR r IN
        SELECT d.id AS payment_id, d.member_id, d.amount,
               d.coverage_start_month, d.coverage_end_month,
               d.donation_month, d.donation_end_month, d.note, d.created_by
        FROM public.donations d
        WHERE NOT EXISTS (
            SELECT 1 FROM public.payment_allocations pa WHERE pa.payment_id = d.id
        )
    LOOP
        SELECT COALESCE(jsonb_agg(
                   jsonb_build_object(
                       'member_id', ph.member_id,
                       'monthly_amount', ph.monthly_amount,
                       'effective_from_month', ph.effective_from_month
                   ) ORDER BY ph.effective_from_month
               ), '[]'::jsonb)
        INTO v_pledge_history
        FROM public.member_pledge_history ph
        WHERE ph.member_id = r.member_id;

        FOR allocation IN
            SELECT * FROM public.calculate_payment_allocation(
                r.payment_id, r.member_id, r.amount,
                COALESCE(r.coverage_start_month, r.donation_month,
                         to_char((SELECT date FROM public.donations WHERE id = r.payment_id), 'YYYY-MM')),
                COALESCE(r.coverage_end_month, r.donation_end_month,
                         r.coverage_start_month, r.donation_month,
                         to_char((SELECT date FROM public.donations WHERE id = r.payment_id), 'YYYY-MM')),
                v_pledge_history
            )
        LOOP
            INSERT INTO public.payment_allocations (
                payment_id, member_id, month, amount, allocation_type, note, created_by
            ) VALUES (
                r.payment_id, r.member_id, allocation.month, allocation.amount,
                allocation.allocation_type, r.note, r.created_by
            );
        END LOOP;
    END LOOP;
END;
$function$;

-- calculate_payment_allocation: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.calculate_payment_allocation(p_payment_id uuid, p_member_id uuid, p_payment_amount numeric, p_coverage_start text, p_coverage_end text, p_pledge_history jsonb)
 RETURNS TABLE(month text, amount numeric, allocation_type text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ DECLARE month_cursor TEXT; month_start DATE; month_end DATE; pledge_amount NUMERIC; remaining NUMERIC; allocated NUMERIC; BEGIN IF p_coverage_start IS NULL OR p_coverage_end IS NULL OR p_coverage_start > p_coverage_end OR p_payment_amount < 0 THEN RETURN; END IF; month_start := to_date(p_coverage_start, 'YYYY-MM'); month_end := to_date(p_coverage_end, 'YYYY-MM'); remaining := p_payment_amount; FOR month_cursor IN SELECT to_char(d, 'YYYY-MM') FROM generate_series(month_start, month_end, INTERVAL '1 month') d LOOP SELECT COALESCE((SELECT (elem->>'monthly_amount')::numeric FROM jsonb_array_elements(COALESCE(p_pledge_history, '[]'::jsonb)) elem WHERE elem->>'effective_from_month' <= month_cursor ORDER BY elem->>'effective_from_month' DESC LIMIT 1), (SELECT monthly_pledge::numeric FROM public.members WHERE id = p_member_id), 0) INTO pledge_amount; pledge_amount := GREATEST(COALESCE(pledge_amount, 0), 0); allocated := LEAST(remaining, pledge_amount); remaining := remaining - allocated; month := month_cursor; amount := allocated; allocation_type := CASE WHEN allocated > 0 THEN 'pledge' ELSE 'unallocated' END; RETURN NEXT; END LOOP; IF remaining > 0 THEN month := NULL; amount := remaining; allocation_type := 'unallocated'; RETURN NEXT; END IF; END; $function$;

-- enforce_member_self_update: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.enforce_member_self_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_token_role TEXT := COALESCE(auth.jwt() ->> 'role', 'anon');
  v_role TEXT;
BEGIN
  IF v_token_role = 'service_role' THEN RETURN NEW; END IF;
  SELECT role INTO v_role FROM public.users WHERE id = auth.uid();
  IF v_role IN ('admin', 'treasurer') THEN RETURN NEW; END IF;
  IF NEW.monthly_pledge IS DISTINCT FROM OLD.monthly_pledge
     OR NEW.status IS DISTINCT FROM OLD.status
     OR NEW.join_date IS DISTINCT FROM OLD.join_date
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'self-service profile updates may only change name, address or phone'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END; $function$;

-- generate_receipt_no: authenticated=EXECUTE, service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.generate_receipt_no()
 RETURNS text
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  seq_num INTEGER;
  seq_text TEXT;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('public.donations.receipt_no'));
  SELECT coalesce(max(cast(nullif(regexp_replace(receipt_no, '[^0-9]', '', 'g'), '') as integer)), 0) + 1
  INTO seq_num FROM public.donations WHERE receipt_no ~ '^R-[0-9]+$';
  seq_text := seq_num::text;
  -- lpad() truncates on the right when the string is already longer than the
  -- target: '991783' -> '9917', which then collides on the UNIQUE index.
  IF length(seq_text) < 4 THEN seq_text := lpad(seq_text, 4, '0'); END IF;
  RETURN 'R-' || seq_text;
END; $function$;

-- get_my_is_approved: anon=EXECUTE, authenticated=EXECUTE, service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.get_my_is_approved()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ BEGIN RETURN COALESCE((SELECT is_approved FROM public.users WHERE id = auth.uid() LIMIT 1), false); END; $function$;

-- get_my_member_id: anon=EXECUTE, authenticated=EXECUTE, service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.get_my_member_id()
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ BEGIN RETURN (SELECT member_id FROM public.users WHERE id = auth.uid() LIMIT 1); END; $function$;

-- get_my_role: anon=EXECUTE, authenticated=EXECUTE, service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.get_my_role()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ BEGIN RETURN (SELECT COALESCE(role, 'member') FROM public.users WHERE id = auth.uid() LIMIT 1); END; $function$;

-- handle_new_user: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.users (id, email, name, phone, role, is_approved)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'name',
    NEW.raw_user_meta_data->>'phone',
    'member',
    false
  );
  RETURN NEW;
END;
$function$;

-- log_audit_event: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.log_audit_event()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_actor_id UUID;
    v_actor_email TEXT;
BEGIN
    v_actor_id := auth.uid();
    v_actor_email := coalesce(auth.jwt() ->> 'email', 'system@foundation.app');

    INSERT INTO public.audit_log (
        actor_id,
        actor_email,
        action,
        target_table,
        target_id,
        details
    ) VALUES (
        v_actor_id,
        v_actor_email,
        TG_OP,
        TG_TABLE_NAME,
        CASE
            WHEN TG_OP = 'DELETE' THEN OLD.id::text
            ELSE NEW.id::text
        END,
        CASE
            WHEN TG_OP = 'INSERT' THEN row_to_json(NEW)::jsonb
            WHEN TG_OP = 'UPDATE' THEN jsonb_build_object('old', row_to_json(OLD)::jsonb, 'new', row_to_json(NEW)::jsonb)
            ELSE row_to_json(OLD)::jsonb
        END
    );
    RETURN NULL;
END;
$function$;

-- reallocate_payment: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.reallocate_payment(p_payment_id uuid, p_amount numeric, p_extra_amount numeric DEFAULT 0, p_coverage_start text DEFAULT NULL::text, p_coverage_end text DEFAULT NULL::text, p_note text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_member_id UUID; v_actor_id UUID; v_pledge_history JSONB; allocation RECORD; v_month_span INT;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Payment amount must be positive'; END IF;
  IF p_extra_amount IS NULL OR p_extra_amount < 0 THEN RAISE EXCEPTION 'Extra amount cannot be negative'; END IF;
  IF p_coverage_start IS NULL OR p_coverage_end IS NULL OR p_coverage_start > p_coverage_end THEN RAISE EXCEPTION 'Coverage month range is required'; END IF;
  IF p_coverage_start !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' OR p_coverage_end !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' THEN
    RAISE EXCEPTION 'Coverage months must be YYYY-MM';
  END IF;
  v_month_span := (split_part(p_coverage_end, '-', 1)::INT - split_part(p_coverage_start, '-', 1)::INT) * 12
                + (split_part(p_coverage_end, '-', 2)::INT - split_part(p_coverage_start, '-', 2)::INT) + 1;
  IF v_month_span < 1 OR v_month_span > 120 THEN RAISE EXCEPTION 'Coverage range must be between 1 and 120 months'; END IF;

  SELECT member_id INTO v_member_id FROM public.donations WHERE id = p_payment_id FOR UPDATE;
  IF v_member_id IS NULL THEN RAISE EXCEPTION 'Payment not found'; END IF;
  v_actor_id := auth.uid();
  SELECT COALESCE(jsonb_agg(jsonb_build_object('member_id', ph.member_id, 'monthly_amount', ph.monthly_amount, 'effective_from_month', ph.effective_from_month)), '[]'::jsonb) INTO v_pledge_history FROM public.member_pledge_history ph WHERE ph.member_id = v_member_id;
  UPDATE public.donations SET amount = p_amount + p_extra_amount, extra_amount = p_extra_amount, coverage_start_month = p_coverage_start, coverage_end_month = p_coverage_end, note = p_note WHERE id = p_payment_id;
  DELETE FROM public.payment_allocations WHERE payment_id = p_payment_id;
  FOR allocation IN SELECT * FROM public.calculate_payment_allocation(p_payment_id, v_member_id, p_amount, p_coverage_start, p_coverage_end, v_pledge_history) LOOP
    INSERT INTO public.payment_allocations(payment_id, member_id, month, amount, allocation_type, note, created_by) VALUES (p_payment_id, v_member_id, allocation.month, allocation.amount, allocation.allocation_type, p_note, v_actor_id);
  END LOOP;
  IF p_extra_amount > 0 THEN INSERT INTO public.payment_allocations(payment_id, member_id, month, amount, allocation_type, note, created_by) VALUES (p_payment_id, v_member_id, NULL, p_extra_amount, 'unallocated', 'Extra amount', v_actor_id); END IF;
END; $function$;

-- save_payment_entry: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.save_payment_entry(p_member_id uuid, p_amount numeric, p_extra_amount numeric DEFAULT 0, p_date date DEFAULT CURRENT_DATE, p_method text DEFAULT 'cash'::text, p_receipt_no text DEFAULT NULL::text, p_coverage_start text DEFAULT NULL::text, p_coverage_end text DEFAULT NULL::text, p_collected_by uuid DEFAULT NULL::uuid, p_note text DEFAULT NULL::text, p_pledge_change_amount numeric DEFAULT NULL::numeric, p_pledge_effective_month text DEFAULT NULL::text, p_pledge_change_note text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_payment_id UUID; v_actor_id UUID; allocation RECORD; v_pledge_history JSONB; v_month_span INT;
BEGIN
  v_actor_id := auth.uid(); p_extra_amount := COALESCE(p_extra_amount, 0);
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Payment amount must be positive'; END IF;
  IF p_extra_amount < 0 THEN RAISE EXCEPTION 'Extra amount cannot be negative'; END IF;
  IF p_coverage_start IS NULL OR p_coverage_end IS NULL OR p_coverage_start > p_coverage_end THEN RAISE EXCEPTION 'Coverage month range is required'; END IF;
  -- BUG-022: the TS preview truncates past 121 months, this engine does not.
  IF p_coverage_start !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' OR p_coverage_end !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' THEN
    RAISE EXCEPTION 'Coverage months must be YYYY-MM';
  END IF;
  v_month_span := (split_part(p_coverage_end, '-', 1)::INT - split_part(p_coverage_start, '-', 1)::INT) * 12
                + (split_part(p_coverage_end, '-', 2)::INT - split_part(p_coverage_start, '-', 2)::INT) + 1;
  IF v_month_span < 1 OR v_month_span > 120 THEN RAISE EXCEPTION 'Coverage range must be between 1 and 120 months'; END IF;
  -- BUG-023: a backdated effective month restates months that are reported.
  IF p_pledge_change_amount IS NOT NULL AND p_pledge_change_amount <= 0 THEN RAISE EXCEPTION 'Pledge amount must be positive'; END IF;
  IF p_pledge_change_amount IS NOT NULL AND p_pledge_effective_month IS NULL THEN RAISE EXCEPTION 'Pledge effective month is required'; END IF;
  IF p_pledge_change_amount IS NOT NULL AND p_pledge_effective_month !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' THEN RAISE EXCEPTION 'Pledge effective month must be YYYY-MM'; END IF;
  IF p_pledge_change_amount IS NOT NULL AND p_pledge_effective_month < p_coverage_start THEN RAISE EXCEPTION 'Pledge effective month cannot be before the coverage start month'; END IF;

  -- BUG-021: the pledge change lands FIRST, so the history read below already
  -- contains it and months on/after the effective month are priced at the new
  -- amount. members.monthly_pledge is updated too because the engine falls
  -- back to it for any month with no history row.
  IF p_pledge_change_amount IS NOT NULL THEN
    UPDATE public.members SET monthly_pledge = p_pledge_change_amount WHERE id = p_member_id;
    INSERT INTO public.member_pledge_history(member_id, monthly_amount, effective_from_month, note, created_by)
    VALUES (p_member_id, p_pledge_change_amount, p_pledge_effective_month, p_pledge_change_note, v_actor_id);
  END IF;

  SELECT COALESCE(jsonb_agg(jsonb_build_object('member_id', ph.member_id, 'monthly_amount', ph.monthly_amount, 'effective_from_month', ph.effective_from_month)), '[]'::jsonb) INTO v_pledge_history FROM public.member_pledge_history ph WHERE ph.member_id = p_member_id;
  INSERT INTO public.donations(member_id, amount, extra_amount, date, method, receipt_no, coverage_start_month, coverage_end_month, note, collected_by, created_by) VALUES (p_member_id, p_amount + p_extra_amount, p_extra_amount, p_date, p_method, p_receipt_no, p_coverage_start, p_coverage_end, p_note, p_collected_by, v_actor_id) RETURNING id INTO v_payment_id;
  FOR allocation IN SELECT * FROM public.calculate_payment_allocation(v_payment_id, p_member_id, p_amount, p_coverage_start, p_coverage_end, v_pledge_history) LOOP
    INSERT INTO public.payment_allocations(payment_id, member_id, month, amount, allocation_type, note, created_by) VALUES (v_payment_id, p_member_id, allocation.month, allocation.amount, allocation.allocation_type, p_note, v_actor_id);
  END LOOP;
  IF p_extra_amount > 0 THEN INSERT INTO public.payment_allocations(payment_id, member_id, month, amount, allocation_type, note, created_by) VALUES (v_payment_id, p_member_id, NULL, p_extra_amount, 'unallocated', 'Extra amount', v_actor_id); END IF;
  RETURN v_payment_id;
END; $function$;

-- set_donation_month: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.set_donation_month()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.donation_month IS NULL THEN
    NEW.donation_month := to_char(NEW.date, 'YYYY-MM');
  END IF;
  RETURN NEW;
END;
$function$;

-- set_receipt_no: service_role=EXECUTE
CREATE OR REPLACE FUNCTION public.set_receipt_no()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.receipt_no IS NULL THEN
    NEW.receipt_no := generate_receipt_no();
  END IF;
  RETURN NEW;
END;
$function$;

-- 8. Triggers
DROP TRIGGER IF EXISTS audit_donations ON public.donations;
CREATE TRIGGER audit_donations AFTER INSERT OR DELETE OR UPDATE ON public.donations FOR EACH ROW EXECUTE FUNCTION log_audit_event();
DROP TRIGGER IF EXISTS tr_set_donation_month ON public.donations;
CREATE TRIGGER tr_set_donation_month BEFORE INSERT ON public.donations FOR EACH ROW EXECUTE FUNCTION set_donation_month();
DROP TRIGGER IF EXISTS tr_set_receipt_no ON public.donations;
CREATE TRIGGER tr_set_receipt_no BEFORE INSERT ON public.donations FOR EACH ROW EXECUTE FUNCTION set_receipt_no();
DROP TRIGGER IF EXISTS audit_expenses ON public.expenses;
CREATE TRIGGER audit_expenses AFTER INSERT OR DELETE OR UPDATE ON public.expenses FOR EACH ROW EXECUTE FUNCTION log_audit_event();
DROP TRIGGER IF EXISTS audit_members ON public.members;
CREATE TRIGGER audit_members AFTER INSERT OR DELETE OR UPDATE ON public.members FOR EACH ROW EXECUTE FUNCTION log_audit_event();
DROP TRIGGER IF EXISTS trg_member_self_update ON public.members;
CREATE TRIGGER trg_member_self_update BEFORE UPDATE ON public.members FOR EACH ROW EXECUTE FUNCTION enforce_member_self_update();

-- 9. Views (security_invoker is emitted per-view where set)
CREATE OR REPLACE VIEW public.account_balances AS
 SELECT a.id,
    a.name,
    a.type,
    a.opening_balance,
    a.is_active,
    a.opening_balance + COALESCE(sum(
        CASE
            WHEN t.direction = 'in'::text THEN t.amount
            ELSE - t.amount
        END), 0::numeric) AS current_balance,
    count(t.id) AS transaction_count
   FROM accounts a
     LEFT JOIN account_transactions t ON t.account_id = a.id
  GROUP BY a.id;
CREATE OR REPLACE VIEW public.donation_summary AS
 SELECT COALESCE(sum(amount), 0::numeric) AS total_amount,
    count(*) AS donation_count
   FROM donations;
ALTER VIEW public.donation_summary SET (security_invoker = true);
CREATE OR REPLACE VIEW public.expense_category_summary AS
 SELECT COALESCE(category, 'অন্যান্য'::text) AS category,
    COALESCE(sum(amount), 0::numeric) AS total_amount
   FROM expenses
  GROUP BY (COALESCE(category, 'অন্যান্য'::text));
ALTER VIEW public.expense_category_summary SET (security_invoker = true);
CREATE OR REPLACE VIEW public.expense_summary AS
 SELECT COALESCE(sum(amount), 0::numeric) AS total_amount,
    count(*) AS expense_count
   FROM expenses;
ALTER VIEW public.expense_summary SET (security_invoker = true);
CREATE OR REPLACE VIEW public.member_directory AS
 SELECT id,
    member_code,
    name,
    join_date,
    status,
    monthly_pledge,
    created_at
   FROM members;
ALTER VIEW public.member_directory SET (security_invoker = true);
CREATE OR REPLACE VIEW public.member_summary AS
 SELECT count(*) AS total_members,
    count(*) FILTER (WHERE status = 'active'::text) AS active_members
   FROM members;
ALTER VIEW public.member_summary SET (security_invoker = true);
CREATE OR REPLACE VIEW public.monthly_collection_summary AS
 WITH RECURSIVE report_window AS (
         SELECT date_trunc('month'::text, CURRENT_DATE::timestamp with time zone)::date AS window_end,
            (date_trunc('month'::text, CURRENT_DATE::timestamp with time zone) - '11 mons'::interval)::date AS window_start
        ), raw_ranges AS (
         SELECT d.id,
            d.member_id,
            d.amount,
            d.date,
            date_trunc('month'::text, COALESCE(to_date(NULLIF(d.coverage_start_month, ''::text), 'YYYY-MM'::text), to_date(NULLIF(d.donation_month, ''::text), 'YYYY-MM'::text), d.date)::timestamp with time zone)::date AS start_month,
            date_trunc('month'::text, COALESCE(to_date(NULLIF(d.coverage_end_month, ''::text), 'YYYY-MM'::text), to_date(NULLIF(d.donation_end_month, ''::text), 'YYYY-MM'::text), to_date(NULLIF(d.coverage_start_month, ''::text), 'YYYY-MM'::text), to_date(NULLIF(d.donation_month, ''::text), 'YYYY-MM'::text), d.date)::timestamp with time zone)::date AS end_month
           FROM donations d
        ), calendar_bounds AS (
         SELECT LEAST(w_1.window_start, COALESCE(min(r.start_month), w_1.window_start)) AS start_month,
            GREATEST(w_1.window_end, COALESCE(max(r.end_month), w_1.window_end)) AS end_month,
            w_1.window_start,
            w_1.window_end
           FROM report_window w_1
             LEFT JOIN raw_ranges r ON true
          GROUP BY w_1.window_start, w_1.window_end
        ), months AS (
         SELECT gs.gs::date AS month
           FROM calendar_bounds b
             CROSS JOIN LATERAL generate_series(b.start_month::timestamp with time zone, b.end_month::timestamp with time zone, '1 mon'::interval) gs(gs)
        ), member_month_pledges AS (
         SELECT months.month,
            m.id AS member_id,
            m.status,
            COALESCE(( SELECT mph.monthly_amount
                   FROM member_pledge_history mph
                  WHERE mph.member_id = m.id AND mph.effective_from_month <= to_char(months.month::timestamp with time zone, 'YYYY-MM'::text)
                  ORDER BY mph.effective_from_month DESC
                 LIMIT 1), m.monthly_pledge, 0::numeric) AS expected_amount
           FROM months
             CROSS JOIN members m
          WHERE m.join_date IS NULL OR date_trunc('month'::text, m.join_date::timestamp with time zone)::date <= months.month
        ), active_targets AS (
         SELECT p.month,
            COALESCE(sum(p.expected_amount) FILTER (WHERE p.status = 'active'::text), 0::numeric) AS target_amount,
            count(*) FILTER (WHERE p.status = 'active'::text) AS active_members
           FROM member_month_pledges p
          GROUP BY p.month
        ), allocated_totals AS (
         SELECT (pa.month || '-01'::text)::date AS month,
            sum(pa.amount) AS collected_amount
           FROM payment_allocations pa
             CROSS JOIN report_window w_1
          WHERE (pa.allocation_type = ANY (ARRAY['pledge'::text, 'advance'::text])) AND pa.month IS NOT NULL AND ((pa.month || '-01'::text)::date) >= w_1.window_start AND ((pa.month || '-01'::text)::date) <= w_1.window_end
          GROUP BY pa.month
        ), legacy_ranges AS (
         SELECT r.id,
            r.member_id,
            r.amount,
            r.date,
            r.start_month,
            r.end_month
           FROM raw_ranges r
          WHERE r.member_id IS NOT NULL AND NOT (EXISTS ( SELECT 1
                   FROM payment_allocations pa
                  WHERE pa.payment_id = r.id))
        ), ordered_donations AS (
         SELECT r.id,
            r.member_id,
            r.amount,
            r.date,
            r.start_month,
            r.end_month,
            row_number() OVER (PARTITION BY r.member_id ORDER BY r.date, r.id) AS donation_seq
           FROM legacy_ranges r
        ), allocation_states(member_id, donation_seq, paid_by_month) AS (
         SELECT DISTINCT r.member_id,
            0::bigint AS int8,
            '{}'::jsonb AS jsonb
           FROM ordered_donations r
        UNION ALL
         SELECT s.member_id,
            d.donation_seq,
            s.paid_by_month || COALESCE(a.updates, '{}'::jsonb)
           FROM allocation_states s
             JOIN ordered_donations d ON d.member_id = s.member_id AND d.donation_seq = (s.donation_seq + 1)
             CROSS JOIN LATERAL ( SELECT COALESCE(jsonb_object_agg(x.month_text, to_jsonb(x.prior_paid + x.allocation)), '{}'::jsonb) AS updates
                   FROM ( SELECT y.month_text,
                            y.prior_paid,
                            GREATEST(LEAST(y.amount - y.required_before, y.capacity), 0::numeric) AS allocation
                           FROM ( SELECT dm.month_text,
                                    dm.amount,
                                    dm.prior_paid,
                                    dm.capacity,
                                    COALESCE(sum(dm.capacity) OVER (ORDER BY dm.month_text ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING), 0::numeric) AS required_before
                                   FROM ( SELECT to_char(gs.month, 'YYYY-MM'::text) AS month_text,
    d.amount,
    COALESCE((s.paid_by_month ->> to_char(gs.month, 'YYYY-MM'::text))::numeric, 0::numeric) AS prior_paid,
    GREATEST(COALESCE(( SELECT p.expected_amount
     FROM member_month_pledges p
    WHERE p.member_id = d.member_id AND p.month = gs.month::date
   LIMIT 1), 0::numeric) - COALESCE((s.paid_by_month ->> to_char(gs.month, 'YYYY-MM'::text))::numeric, 0::numeric), 0::numeric) AS capacity
   FROM generate_series(d.start_month::timestamp with time zone, d.end_month::timestamp with time zone, '1 mon'::interval) gs(month)) dm) y) x) a
        ), final_member_allocations AS (
         SELECT DISTINCT ON (allocation_states.member_id) allocation_states.member_id,
            allocation_states.paid_by_month
           FROM allocation_states
          ORDER BY allocation_states.member_id, allocation_states.donation_seq DESC
        ), legacy_totals AS (
         SELECT (items.key || '-01'::text)::date AS month,
            sum(items.value::numeric) AS collected_amount
           FROM final_member_allocations f
             CROSS JOIN LATERAL jsonb_each_text(f.paid_by_month) items(key, value)
             CROSS JOIN report_window w_1
          WHERE ((items.key || '-01'::text)::date) >= w_1.window_start AND ((items.key || '-01'::text)::date) <= w_1.window_end
          GROUP BY items.key
        ), donation_totals AS (
         SELECT u.month,
            sum(u.collected_amount) AS collected_amount
           FROM ( SELECT allocated_totals.month,
                    allocated_totals.collected_amount
                   FROM allocated_totals
                UNION ALL
                 SELECT legacy_totals.month,
                    legacy_totals.collected_amount
                   FROM legacy_totals) u
          GROUP BY u.month
        ), expense_totals AS (
         SELECT date_trunc('month'::text, e.date::timestamp with time zone)::date AS month,
            COALESCE(sum(e.amount), 0::numeric) AS expense_amount
           FROM expenses e
             CROSS JOIN report_window w_1
          WHERE e.date >= w_1.window_start
          GROUP BY (date_trunc('month'::text, e.date::timestamp with time zone)::date)
        )
 SELECT at.month,
    at.target_amount,
    COALESCE(dt.collected_amount, 0::numeric) AS collected_amount,
    GREATEST(at.target_amount - COALESCE(dt.collected_amount, 0::numeric), 0::numeric) AS due_amount,
        CASE
            WHEN at.target_amount > 0::numeric THEN round(COALESCE(dt.collected_amount, 0::numeric) / at.target_amount * 100::numeric, 2)
            ELSE 0::numeric
        END AS collection_rate,
    at.active_members,
    COALESCE(et.expense_amount, 0::numeric) AS expense_amount,
    COALESCE(dt.collected_amount, 0::numeric) - COALESCE(et.expense_amount, 0::numeric) AS net_balance
   FROM active_targets at
     LEFT JOIN donation_totals dt ON dt.month = at.month
     LEFT JOIN expense_totals et ON et.month = at.month
     CROSS JOIN report_window w
  WHERE at.month >= w.window_start AND at.month <= w.window_end
  ORDER BY at.month;
ALTER VIEW public.monthly_collection_summary SET (security_invoker = true);

-- 10. Grants
--     Supabase's default grants are permissive for anon/authenticated:
--     RLS on the tables (section 5) is the real boundary for tables, and
--     EXECUTE (section 7) is the boundary for RPCs.
GRANT DELETE ON public.account_balances TO anon, authenticated, service_role;
GRANT INSERT ON public.account_balances TO anon, authenticated, service_role;
GRANT REFERENCES ON public.account_balances TO anon, authenticated, service_role;
GRANT SELECT ON public.account_balances TO anon, authenticated, service_role;
GRANT TRIGGER ON public.account_balances TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.account_balances TO anon, authenticated, service_role;
GRANT UPDATE ON public.account_balances TO anon, authenticated, service_role;
GRANT DELETE ON public.account_transactions TO anon, authenticated, service_role;
GRANT INSERT ON public.account_transactions TO anon, authenticated, service_role;
GRANT REFERENCES ON public.account_transactions TO anon, authenticated, service_role;
GRANT SELECT ON public.account_transactions TO anon, authenticated, service_role;
GRANT TRIGGER ON public.account_transactions TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.account_transactions TO anon, authenticated, service_role;
GRANT UPDATE ON public.account_transactions TO anon, authenticated, service_role;
GRANT DELETE ON public.accounts TO anon, authenticated, service_role;
GRANT INSERT ON public.accounts TO anon, authenticated, service_role;
GRANT REFERENCES ON public.accounts TO anon, authenticated, service_role;
GRANT SELECT ON public.accounts TO anon, authenticated, service_role;
GRANT TRIGGER ON public.accounts TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.accounts TO anon, authenticated, service_role;
GRANT UPDATE ON public.accounts TO anon, authenticated, service_role;
GRANT DELETE ON public.audit_log TO anon, authenticated, service_role;
GRANT INSERT ON public.audit_log TO anon, authenticated, service_role;
GRANT REFERENCES ON public.audit_log TO anon, authenticated, service_role;
GRANT SELECT ON public.audit_log TO anon, authenticated, service_role;
GRANT TRIGGER ON public.audit_log TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.audit_log TO anon, authenticated, service_role;
GRANT UPDATE ON public.audit_log TO anon, authenticated, service_role;
GRANT DELETE ON public.donation_summary TO service_role;
GRANT INSERT ON public.donation_summary TO service_role;
GRANT REFERENCES ON public.donation_summary TO anon, authenticated, service_role;
GRANT SELECT ON public.donation_summary TO authenticated, service_role;
GRANT TRIGGER ON public.donation_summary TO service_role;
GRANT TRUNCATE ON public.donation_summary TO service_role;
GRANT UPDATE ON public.donation_summary TO service_role;
GRANT DELETE ON public.donations TO anon, authenticated, service_role;
GRANT INSERT ON public.donations TO anon, authenticated, service_role;
GRANT REFERENCES ON public.donations TO anon, authenticated, service_role;
GRANT SELECT ON public.donations TO anon, authenticated, service_role;
GRANT TRIGGER ON public.donations TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.donations TO anon, authenticated, service_role;
GRANT UPDATE ON public.donations TO anon, authenticated, service_role;
GRANT DELETE ON public.expense_categories TO anon, authenticated, service_role;
GRANT INSERT ON public.expense_categories TO anon, authenticated, service_role;
GRANT REFERENCES ON public.expense_categories TO anon, authenticated, service_role;
GRANT SELECT ON public.expense_categories TO anon, authenticated, service_role;
GRANT TRIGGER ON public.expense_categories TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.expense_categories TO anon, authenticated, service_role;
GRANT UPDATE ON public.expense_categories TO anon, authenticated, service_role;
GRANT DELETE ON public.expense_category_summary TO service_role;
GRANT INSERT ON public.expense_category_summary TO service_role;
GRANT REFERENCES ON public.expense_category_summary TO anon, authenticated, service_role;
GRANT SELECT ON public.expense_category_summary TO authenticated, service_role;
GRANT TRIGGER ON public.expense_category_summary TO service_role;
GRANT TRUNCATE ON public.expense_category_summary TO service_role;
GRANT UPDATE ON public.expense_category_summary TO service_role;
GRANT DELETE ON public.expense_summary TO service_role;
GRANT INSERT ON public.expense_summary TO service_role;
GRANT REFERENCES ON public.expense_summary TO anon, authenticated, service_role;
GRANT SELECT ON public.expense_summary TO authenticated, service_role;
GRANT TRIGGER ON public.expense_summary TO service_role;
GRANT TRUNCATE ON public.expense_summary TO service_role;
GRANT UPDATE ON public.expense_summary TO service_role;
GRANT DELETE ON public.expenses TO anon, authenticated, service_role;
GRANT INSERT ON public.expenses TO anon, authenticated, service_role;
GRANT REFERENCES ON public.expenses TO anon, authenticated, service_role;
GRANT SELECT ON public.expenses TO anon, authenticated, service_role;
GRANT TRIGGER ON public.expenses TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.expenses TO anon, authenticated, service_role;
GRANT UPDATE ON public.expenses TO anon, authenticated, service_role;
GRANT DELETE ON public.member_directory TO anon, authenticated, service_role;
GRANT INSERT ON public.member_directory TO anon, authenticated, service_role;
GRANT REFERENCES ON public.member_directory TO anon, authenticated, service_role;
GRANT SELECT ON public.member_directory TO anon, authenticated, service_role;
GRANT TRIGGER ON public.member_directory TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.member_directory TO anon, authenticated, service_role;
GRANT UPDATE ON public.member_directory TO anon, authenticated, service_role;
GRANT DELETE ON public.member_pledge_history TO anon, authenticated, service_role;
GRANT INSERT ON public.member_pledge_history TO anon, authenticated, service_role;
GRANT REFERENCES ON public.member_pledge_history TO anon, authenticated, service_role;
GRANT SELECT ON public.member_pledge_history TO anon, authenticated, service_role;
GRANT TRIGGER ON public.member_pledge_history TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.member_pledge_history TO anon, authenticated, service_role;
GRANT UPDATE ON public.member_pledge_history TO anon, authenticated, service_role;
GRANT DELETE ON public.member_summary TO service_role;
GRANT INSERT ON public.member_summary TO service_role;
GRANT REFERENCES ON public.member_summary TO anon, authenticated, service_role;
GRANT SELECT ON public.member_summary TO authenticated, service_role;
GRANT TRIGGER ON public.member_summary TO service_role;
GRANT TRUNCATE ON public.member_summary TO service_role;
GRANT UPDATE ON public.member_summary TO service_role;
GRANT DELETE ON public.members TO anon, authenticated, service_role;
GRANT INSERT ON public.members TO anon, authenticated, service_role;
GRANT REFERENCES ON public.members TO anon, authenticated, service_role;
GRANT SELECT ON public.members TO anon, authenticated, service_role;
GRANT TRIGGER ON public.members TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.members TO anon, authenticated, service_role;
GRANT UPDATE ON public.members TO anon, authenticated, service_role;
GRANT DELETE ON public.monthly_collection_summary TO service_role;
GRANT INSERT ON public.monthly_collection_summary TO service_role;
GRANT REFERENCES ON public.monthly_collection_summary TO anon, authenticated, service_role;
GRANT SELECT ON public.monthly_collection_summary TO authenticated, service_role;
GRANT TRIGGER ON public.monthly_collection_summary TO service_role;
GRANT TRUNCATE ON public.monthly_collection_summary TO service_role;
GRANT UPDATE ON public.monthly_collection_summary TO service_role;
GRANT DELETE ON public.notices TO anon, authenticated, service_role;
GRANT INSERT ON public.notices TO anon, authenticated, service_role;
GRANT REFERENCES ON public.notices TO anon, authenticated, service_role;
GRANT SELECT ON public.notices TO authenticated, service_role;
GRANT TRIGGER ON public.notices TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.notices TO anon, authenticated, service_role;
GRANT UPDATE ON public.notices TO anon, authenticated, service_role;
GRANT DELETE ON public.notifications TO anon, authenticated, service_role;
GRANT INSERT ON public.notifications TO anon, authenticated, service_role;
GRANT REFERENCES ON public.notifications TO anon, authenticated, service_role;
GRANT SELECT ON public.notifications TO anon, authenticated, service_role;
GRANT TRIGGER ON public.notifications TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.notifications TO anon, authenticated, service_role;
GRANT UPDATE ON public.notifications TO anon, authenticated, service_role;
GRANT DELETE ON public.payment_allocations TO anon, authenticated, service_role;
GRANT INSERT ON public.payment_allocations TO anon, authenticated, service_role;
GRANT REFERENCES ON public.payment_allocations TO anon, authenticated, service_role;
GRANT SELECT ON public.payment_allocations TO anon, authenticated, service_role;
GRANT TRIGGER ON public.payment_allocations TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.payment_allocations TO anon, authenticated, service_role;
GRANT UPDATE ON public.payment_allocations TO anon, authenticated, service_role;
GRANT DELETE ON public.reminder_log TO anon, authenticated, service_role;
GRANT INSERT ON public.reminder_log TO anon, authenticated, service_role;
GRANT REFERENCES ON public.reminder_log TO anon, authenticated, service_role;
GRANT SELECT ON public.reminder_log TO anon, authenticated, service_role;
GRANT TRIGGER ON public.reminder_log TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.reminder_log TO anon, authenticated, service_role;
GRANT UPDATE ON public.reminder_log TO anon, authenticated, service_role;
GRANT DELETE ON public.users TO anon, authenticated, service_role;
GRANT INSERT ON public.users TO anon, authenticated, service_role;
GRANT REFERENCES ON public.users TO anon, authenticated, service_role;
GRANT SELECT ON public.users TO anon, authenticated, service_role;
GRANT TRIGGER ON public.users TO anon, authenticated, service_role;
GRANT TRUNCATE ON public.users TO anon, authenticated, service_role;
GRANT UPDATE ON public.users TO anon, authenticated, service_role;

